---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: TAARIFA_KENYA-total-portal
  name: TAARIFA_KENYA-total-portal-deployment
  namespace: TAARIFA_KENYAs
spec:
  selector:
    matchLabels:
      app: TAARIFA_KENYA-total-portal
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: TAARIFA_KENYA-total-portal
    spec:
      containers:
        - name: TAARIFA_KENYA-total-portal
          image: ImageName
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          env: 
            - name: 'REACT_APP_BASE'
              value: 'https://lbtotal.mfs.co.ke'
            - name: 'REACT_APP_KEY'
              value: 'a1bed52870ec4338abf13513ad29875e'

---
apiVersion: v1
kind: Service
metadata:
  name: TAARIFA_KENYA-total-portal-service
  namespace: TAARIFA_KENYAs
  labels:
    run: TAARIFA_KENYA-total-portal-service
spec:
  type: NodePort
  ports:
    - name: TAARIFA_KENYA-total-portal-port
      port: 80
      protocol: TCP
      nodePort: 30561
  selector:
    app: TAARIFA_KENYA-total-portal
